export const typesBoard = {
  ADD_COLUMN: 'ADD_COLUMN',
  REMOVE_COLUMN: 'REMOVE_COLUMN',
  REORDER_COLUMNS: 'REORDER_COLUMNS',
  UPDATE_BOARD_TITLE: 'UPDATE_BOARD_TITLE'
}

export const typesColumn = {
  ADD_COLUMN: 'ADD_COLUMN',
  ADD_TASK: 'ADD_TASK',
  MOVE_TASK: 'MOVE_TASK',
  REMOVE_COLUMN: 'REMOVE_COLUMN',
  REMOVE_TASK: 'REMOVE_TASK',
  REORDER_TASKS: 'REORDER_TASKS',
  UPDATE_COLUMN_TITLE: 'UPDATE_COLUMN_TITLE'
}

export const typesTasks = {
  ADD_TASK: 'ADD_TASK',
  REMOVE_TASK: 'REMOVE_TASK',
  UPDATE_TASK: 'UPDATE_TASK'
}

export const typesDnd = {
  DRAG_TYPE_COLUMN: 'DRAG_TYPE_COLUMN',
  DRAG_TYPE_TASK: 'DRAG_TYPE_TASK'
}
