/* KANBAN ACTIONS */
const ADD_COLUMN = 'ADD_COLUMN'
const ADD_TO_COLUMN = 'ADD_TO_COLUMN'
const MOVE_TASK = 'MOVE_TASK'
const REMOVE_COLUMN = 'REMOVE_COLUMN'
const REORDER_COLUMNS = 'REORDER_COLUMNS'
const REORDER_TASKS = 'REORDER_TASKS'
const REMOVE_FROM_COLUMN = 'REMOVE_FROM_COLUMN'
const UPDATE_COLUMN_TITLE = 'UPDATE_COLUMN_TITLE'
const UPDATE_BOARD_TITLE = 'UPDATE_BOARD_TITLE'

/* TASK ACTIONS */
const ADD_TASK = 'ADD_TASK'
const REMOVE_TASK = 'REMOVE_TASK'
const UPDATE_TASK = 'UPDATE_TASK'

/* DND TYPES */
const DRAG_TYPE_COLUMN = 'DRAG_TYPE_COLUMN'
const DRAG_TYPE_TASK = 'DRAG_TYPE_TASK'

export const typesKanban = {
  ADD_COLUMN,
  ADD_TO_COLUMN,
  MOVE_TASK,
  REMOVE_COLUMN,
  REORDER_COLUMNS,
  REORDER_TASKS,
  REMOVE_FROM_COLUMN,
  UPDATE_COLUMN_TITLE,
  UPDATE_BOARD_TITLE
}

export const typesTasks = {
  ADD_TASK,
  REMOVE_TASK,
  UPDATE_TASK
}

export const typesDnd = {
  DRAG_TYPE_COLUMN,
  DRAG_TYPE_TASK
}
